package com.company.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ValidationResult implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "error code")
	private String errorCode;
	@org.kie.api.definition.type.Label(value = "Error Text")
	private String errorText;

	public ValidationResult() {
	}

    public ValidationResult(String errorCode) {
        this.errorCode = errorCode;
	}


	public String getErrorCode() {
		return this.errorCode;
	}

	public void setErrorCode(String errorCode) {
		this.errorCode = errorCode;
	}

	public String getErrorText() {
		return this.errorText;
	}

	public void setErrorText(String errorText) {
		this.errorText = errorText;
	}

	public ValidationResult(String errorCode,
                            String errorText) {
		this.errorCode = errorCode;
		this.errorText = errorText;
	}

	@Override
	public String toString() {
		return "ValidationResult{" +
				"errorCode='" + errorCode + '\'' +
				", errorText='" + errorText + '\'' +
				'}';
	}
}